apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework6
spec:
  selector:
    matchLabels:
      app: busy-multi
  template:
    metadata:
      labels:
        app: busy-multi
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: testvolume
          mountPath: /test1
      volumes:
        - name: testvolume
          hostPath: 
            path: /var/log
          